fix: create "~/.sherlock/" directory if it doesn't exist (#92)
If `~/.sherlock/` doesn't exist, the program panics when trying to open the logfile.

thread '<unnamed>' panicked at src/utils/logging.rs:18:10:
src/utils/logging.rs:18 - Failed to open logfile: Os { code: 2, kind: NotFound, message: "No such file or directory" }