fix: Exec command wasn't split on quoted arguments (#107)
* fix: fixed missing emoji launcher icon

* fix: create "~/.sherlock/" directory if it doesn't exist (#92)

If `~/.sherlock/` doesn't exist, the program panics when trying to open the logfile.

thread '<unnamed>' panicked at src/utils/logging.rs:18:10:
src/utils/logging.rs:18 - Failed to open logfile: Os { code: 2, kind: NotFound, message: "No such file or directory" }

* fix: fixed launchers not refreshing in daemon mode

* Update config.md (#104)

* fix: Exec command wasn't split on quoted arguments

* impr: cargo fmt

---------

Co-authored-by: Sebastian Kootz <skxxtz@gmail.com>
Co-authored-by: David Marchante <6660202+iovis@users.noreply.github.com>
Co-authored-by: Daniel Kusai <dan.kusai.star.123234@gmail.com>
Co-authored-by: Sebastian Kootz <63540046+Skxxtz@users.noreply.github.com>